name: Gradle CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: ShadowJar
      run: ./gradlew shadowJar
    - name: Shadow :mirai-console separately
      run: cd mirai-console && ../gradlew shadowJar
    - name: Upload artifact mirai-console
      uses: actions/upload-artifact@v2
      with:
        name: mirai-console  
        path: mirai-console/build/libs/*.jar
    - name: Upload artifact mirai-console-graphical
      uses: actions/upload-artifact@v2
      with:
        name: mirai-console-graphical  
        path: mirai-console-graphical/build/libs/*.jar
    - name: Upload artifact mirai-console-terminal
      uses: actions/upload-artifact@v2
      with:
        name: mirai-console-terminal
        path: mirai-console-terminal/build/libs/*.jar
